**NumPy (Numerical Python)**

- It is used for scientific calculations 
- It allows high performance work on arrays, multidimensional arrays and matrices.
- It holds fixed data type

In [1]:
#### Importing NumPy Library ####

import numpy as np

**Multiplying Elements of Two Lists: Comparing Classic Python Method and NumPy Array**

In [2]:
###### Classic Python Method

a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

ab = []

for i in range(0, len(a)): #create a range 
    ab.append(a[i] * b[i]) #multiply the elements, and append it to ab

print(ab) ##output: [2, 6, 12, 20]


###### Same Operation with NumPY

###convert the lists to NumPy array, then use a * b

a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

a * b ##output: [2, 6, 12, 20]

[2, 6, 12, 20]


array([ 2,  6, 12, 20])

**Creating NumPy Arrays**

In [3]:
import numpy as np

np.array([1, 2, 3, 4])

type(np.array([1, 2, 3, 4])) ##output: numpy.ndarray



## Creating an Array of Zeros with Type int

np.zeros(3, dtype=int) ##output: array([0, 0, 0])




## Creating a 2D array with a specific shape

matrix = np.zeros((4, 4))

##output: array([[0., 0., 0., 0.],
##       [0., 0., 0., 0.],
##       [0., 0., 0., 0.],
##       [0., 0., 0., 0.]])



##Creating an array of 10 random integers between 0 and 10

np.random.randint(0, 10, size=10) 

##output: array([9, 1, 3, 7, 6, 1, 1, 6, 4, 4])




##Testing array for matrix operations

test_matrix = np.array([[1, 2], [3, 4]])

##output: array([[1, 2],
##       [3, 4]])





##Preallocating an array for storing results in a loop

result_array = np.zeros(1000) 
##output: 1,000 elements array([0., 0., .......


**Attributes of NumPy Arrays**

ndim:  -dimension info(1D, 2D, 3D)

shape: -size of each dimension(rows & columns for 2D)

size:  -total number of elements

dtype: -data type of elements

In [4]:
a = np.random.randint(10, size=5)

a.ndim ##output: 1
a.shape ##output: (5,)
a.size ##output: 5
a.dtype ##output: dtype('int64')

dtype('int64')

**RESHAPING**

The reshaping method is used when you want to change the size of a NumPy array.

In [5]:
## Converting a 1D array to a 2D matrix with 3 rows and columns ##

np.random.randint(1, 10, size=9)
np.random.randint(1, 10, size=9).reshape(3, 3) 



## with assigning to a variable ##

ar = np.random.randint(1, 10, size=9)
ar.reshape(3, 3)


array([[7, 6, 7],
       [5, 8, 8],
       [5, 9, 9]])

**Index Selection and Fancy Indexing**



In [6]:
## Index selection on 1D array ##

a = np.random.randint(10, size=10) #1D array

a[0] ##output: first element of the array
a[0:5]  ##output: first 5 elements  - slicing method -
a[0] = 999 ##changing the first element




## Index selection on 2D array ##

m = np.random.randint(10, size=(3, 5)) #2D array
m[0, 0] ##output: element on the first row & column

### slicing method on 2D ###

m[:, 0]        ## select all rows and first column
m[1, :]        ## select second row and all columns



## Fancy Index Example##

v = np.arange(0, 30, 3)  # Create a NumPy array with values from 0 to 27, with a step of 3


catch = [1, 2, 3]  # Define an array of indices

v[catch] # Use fancy indexing to select elements from the array 'v'


v[catch] = [30, 60, 90] # Use fancy indexing to modify elements

**Conditions on NumPy**

In [7]:
############ with Loops




v = np.array([1, 2, 3, 4, 5])

ab = []
for i in v:           ## Loop through each element in the array 'v'
    if i < 3:         ## Check if the current element 'i' is less than 3
        ab.append(i)  ## If the condition is True, append the element to the list 'ab'
print(ab)             ##output: [1, 2]





############ with NumPY

v = np.array([1, 2, 3, 4, 5])

v[v < 3] ##output: array([1, 2])


[1, 2]


array([1, 2])

**Mathematical Operations on NumPy**

In [8]:
v = np.array([1, 2, 3, 4, 5])

## with operators:

v / 5             ##output: array([0.2, 0.4, 0.6, 0.8, 1. ])   - divides each element
v * 5 / 10        ##output: array([0.5, 1. , 1.5, 2. , 2.5])   - multiplies, then divides each element
v ** 2            ##output: array([ 1,  4,  9, 16, 25])        - squares each element
v - 1             ##output: array([0, 1, 2, 3, 4])             - subtracts 1 from each element

## with methods:

np.subtract(v, 1) ##output: array([0, 1, 2, 3, 4])  - subtracts 1 from each element
np.add(v, 1)      ##output: array([2, 3, 4, 5, 6])  - adds 1 to each element
np.mean(v)        ##output: 3.0                     - gives mean value of array v
np.sum(v)         ##output: 15                      - sums the elements of array v
np.min(v)         ##output: 1                       - gives minimum value of array v
np.max(v)         ##output: 5                       - gives maximum value of array v
np.var(v)         ##output: 2.0                     - gives variance of array v

2.0